### ISSUE TITLE
2a

### ISSUE THREAD

**Issue by rdawes1** [viableindustries/WatershedStewardsAcademy-CleanWaterCommunities#10]
Why did we switch to length x width rather than just straight square footage? I’m sure there was a reason; I just can’t recall it right now!

**Comment by joshuapowell** [comment]
The reason we switched to length and width were because of Bryan's new calculations.

The new calculations require that these items are split so that we properly calculate "Bottom Surface Area" which in turn affects our Ponding Volume and Storage Soil Volume which are needed to calculate our Total Volume and finally give us our % Water Quality Volume. 

% Water Quality Volume is the important one because that gives us the number we need to calculate the additional Credit.
